spring.application.name=devtasker-api

# Banco de dados
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/devtasker_db}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA e Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
security.jwt.secret=${JWT_SECRET}
security.jwt.issuer=devtasker-api
security.jwt.access-token-minutes=30