CREATE TABLE project_labels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    name VARCHAR(30) NOT NULL,
    normalized_name VARCHAR(30) NOT NULL,
    color VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    archived_at TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_project_labels_project
        FOREIGN KEY (project_id)
        REFERENCES projects (id)
        ON DELETE CASCADE,

    CONSTRAINT ck_project_labels_color
        CHECK (color IN ('GREEN', 'BLUE', 'VIOLET', 'AMBER', 'RED', 'CYAN', 'GRAY'))
);

CREATE UNIQUE INDEX uk_project_labels_active_name
    ON project_labels (project_id, normalized_name)
    WHERE archived_at IS NULL;

CREATE INDEX idx_project_labels_project_id
    ON project_labels (project_id);

WITH distinct_labels AS (
    SELECT
        board.project_id,
        LOWER(TRIM(task_label.label)) AS normalized_name,
        MIN(TRIM(task_label.label)) AS name,
        ROW_NUMBER() OVER (
            PARTITION BY board.project_id
            ORDER BY LOWER(TRIM(task_label.label))
        ) AS color_position
    FROM task_labels task_label
    JOIN tasks task ON task.id = task_label.task_id
    JOIN board_columns board_column ON board_column.id = task.column_id
    JOIN boards board ON board.id = board_column.board_id
    GROUP BY board.project_id, LOWER(TRIM(task_label.label))
)
INSERT INTO project_labels (project_id, name, normalized_name, color)
SELECT
    project_id,
    name,
    normalized_name,
    CASE MOD(color_position - 1, 7)
        WHEN 0 THEN 'GREEN'
        WHEN 1 THEN 'BLUE'
        WHEN 2 THEN 'VIOLET'
        WHEN 3 THEN 'AMBER'
        WHEN 4 THEN 'RED'
        WHEN 5 THEN 'CYAN'
        ELSE 'GRAY'
    END
FROM distinct_labels;

CREATE TABLE task_label_assignments (
    task_id BIGINT NOT NULL,
    label_id BIGINT NOT NULL,
    position INTEGER NOT NULL,

    CONSTRAINT pk_task_label_assignments
        PRIMARY KEY (task_id, position),

    CONSTRAINT uk_task_label_assignments_task_label
        UNIQUE (task_id, label_id),

    CONSTRAINT fk_task_label_assignments_task
        FOREIGN KEY (task_id)
        REFERENCES tasks (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_task_label_assignments_label
        FOREIGN KEY (label_id)
        REFERENCES project_labels (id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_task_label_assignments_position
        CHECK (position >= 0)
);

INSERT INTO task_label_assignments (task_id, label_id, position)
SELECT
    task_label.task_id,
    project_label.id,
    MIN(task_label.position)
FROM task_labels task_label
JOIN tasks task ON task.id = task_label.task_id
JOIN board_columns board_column ON board_column.id = task.column_id
JOIN boards board ON board.id = board_column.board_id
JOIN project_labels project_label
    ON project_label.project_id = board.project_id
   AND project_label.normalized_name = LOWER(TRIM(task_label.label))
GROUP BY task_label.task_id, project_label.id;

CREATE INDEX idx_task_label_assignments_label_id
    ON task_label_assignments (label_id);

DROP TABLE task_labels;
