CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(1000),
    owner_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_projects_owner
        FOREIGN KEY (owner_id)
        REFERENCES users (id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_projects_owner_id
    ON projects (owner_id);


CREATE TABLE project_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(30) NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_project_members_project
        FOREIGN KEY (project_id)
        REFERENCES projects (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_project_members_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT uk_project_members_project_user
        UNIQUE (project_id, user_id),

    CONSTRAINT ck_project_members_role
        CHECK (role IN ('OWNER', 'ADMIN', 'MEMBER', 'VIEWER'))
);

CREATE INDEX idx_project_members_user_id
    ON project_members (user_id);

CREATE INDEX idx_project_members_project_id
    ON project_members (project_id);


CREATE TABLE boards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_boards_project
        FOREIGN KEY (project_id)
        REFERENCES projects (id)
        ON DELETE CASCADE,

    CONSTRAINT uk_boards_project_name
        UNIQUE (project_id, name)
);

CREATE INDEX idx_boards_project_id
    ON boards (project_id);


CREATE TABLE board_columns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(30) NOT NULL,
    position INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_board_columns_board
        FOREIGN KEY (board_id)
        REFERENCES boards (id)
        ON DELETE CASCADE,

    CONSTRAINT uk_board_columns_board_name
        UNIQUE (board_id, name),

    CONSTRAINT uk_board_columns_board_position
        UNIQUE (board_id, position),

    CONSTRAINT ck_board_columns_position
        CHECK (position >= 0),

    CONSTRAINT ck_board_columns_category
        CHECK (
            category IN (
                'BACKLOG',
                'TODO',
                'DOING',
                'REVIEW',
                'DONE'
            )
        )
);

CREATE INDEX idx_board_columns_board_id
    ON board_columns (board_id);