CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    column_id BIGINT NOT NULL,
    creator_id BIGINT NOT NULL,
    assignee_id BIGINT,

    title VARCHAR(180) NOT NULL,
    description VARCHAR(4000),
    priority VARCHAR(20) NOT NULL,
    due_date DATE,
    position INTEGER NOT NULL,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    archived_at TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_tasks_column
        FOREIGN KEY (column_id)
        REFERENCES board_columns (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_tasks_creator
        FOREIGN KEY (creator_id)
        REFERENCES users (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_tasks_assignee
        FOREIGN KEY (assignee_id)
        REFERENCES users (id)
        ON DELETE SET NULL,

    CONSTRAINT ck_tasks_priority
        CHECK (
            priority IN (
                'LOW',
                'MEDIUM',
                'HIGH',
                'URGENT'
            )
        ),

    CONSTRAINT ck_tasks_position
        CHECK (position >= 0)
);

CREATE INDEX idx_tasks_column_id
    ON tasks (column_id);

CREATE INDEX idx_tasks_creator_id
    ON tasks (creator_id);

CREATE INDEX idx_tasks_assignee_id
    ON tasks (assignee_id);

CREATE INDEX idx_tasks_due_date
    ON tasks (due_date);

CREATE UNIQUE INDEX uk_tasks_active_column_position
    ON tasks (column_id, position)
    WHERE archived_at IS NULL;