ALTER TABLE users
    ADD COLUMN email_verified_at TIMESTAMP WITH TIME ZONE;

-- As contas que já existiam antes desta funcionalidade
-- são consideradas verificadas.
UPDATE users
SET email_verified_at = created_at
WHERE email_verified_at IS NULL;

CREATE TABLE email_verification_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    user_id BIGINT NOT NULL,

    code_hash VARCHAR(255) NOT NULL,

    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,

    attempt_count INTEGER NOT NULL DEFAULT 0,

    last_sent_at TIMESTAMP WITH TIME ZONE NOT NULL,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL,

    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_email_verification_codes_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT uk_email_verification_codes_user
        UNIQUE (user_id),

    CONSTRAINT ck_email_verification_attempt_count
        CHECK (attempt_count >= 0)
);

CREATE INDEX idx_email_verification_codes_expires_at
    ON email_verification_codes (expires_at);