ALTER TABLE users
    ADD COLUMN credential_version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE users
    ADD CONSTRAINT ck_users_credential_version
        CHECK (credential_version >= 0);

CREATE TABLE password_recovery_challenges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    user_id BIGINT NOT NULL,

    public_id UUID NOT NULL,

    code_hash VARCHAR(255) NOT NULL,

    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,

    attempt_count INTEGER NOT NULL DEFAULT 0,

    last_sent_at TIMESTAMP WITH TIME ZONE NOT NULL,

    verified_at TIMESTAMP WITH TIME ZONE,

    reset_token_hash VARCHAR(255),

    reset_token_expires_at TIMESTAMP WITH TIME ZONE,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL,

    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_password_recovery_challenges_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT uk_password_recovery_challenges_user
        UNIQUE (user_id),

    CONSTRAINT uk_password_recovery_challenges_public_id
        UNIQUE (public_id),

    CONSTRAINT uk_password_recovery_challenges_reset_token_hash
        UNIQUE (reset_token_hash),

    CONSTRAINT ck_password_recovery_challenges_attempt_count
        CHECK (attempt_count >= 0)
);

CREATE INDEX idx_password_recovery_challenges_expires_at
    ON password_recovery_challenges (expires_at);

CREATE INDEX idx_password_recovery_challenges_reset_token_expires_at
    ON password_recovery_challenges (reset_token_expires_at);
