CREATE TABLE project_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    invited_by_id BIGINT NOT NULL,
    invited_email VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    status VARCHAR(30) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    responded_at TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_project_invitations_project
        FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_project_invitations_invited_by
        FOREIGN KEY (invited_by_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT uk_project_invitations_token_hash UNIQUE (token_hash),
    CONSTRAINT ck_project_invitations_role
        CHECK (role IN ('ADMIN', 'MEMBER', 'VIEWER')),
    CONSTRAINT ck_project_invitations_status
        CHECK (status IN ('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED'))
);

CREATE INDEX idx_project_invitations_project_status
    ON project_invitations (project_id, status, created_at DESC);

CREATE INDEX idx_project_invitations_email_status
    ON project_invitations (invited_email, status);

CREATE UNIQUE INDEX uk_project_invitations_pending_email
    ON project_invitations (project_id, invited_email)
    WHERE status = 'PENDING';
